dist: xenial
language: go
os: linux

go:
  - 1.14.x

git:
  depth: false

services:
  - docker

env:
  global:
    - STRUCTOR_VERSION=v1.10.0
    - STRUCTOR_LATEST_TAG=v0.1.0
    - GO111MODULE=on

install:
  - sudo -E apt-get -yq update
  - >
    sudo -E apt-get -yq --no-install-suggests --no-install-recommends install \
      build-essential \
      autoconf \
      libtool \
      bison \
      flex \
      make \
      libmagic-dev \
      libssl-dev \
      libpcap-dev \
      g++-multilib \
      docker-ce=${DOCKER_VERSION}*
  - sudo -E ./script/travis_setup.sh
  - sudo -E ./script/install_yara.sh

before_script:
  - go mod download

script:
  - make test-race

before_deploy:
  - ./script/before_deploy.sh

deploy:
  - provider: releases
    api_key: ${GITHUB_TOKEN}
    file_glob: true
    file: build/mole_*
    skip_cleanup: true
    on:
      tags: true

  - provider: pages
    token: ${GITHUB_TOKEN}
    edge: false
    strategy: git
    local_dir: site
    skip_cleanup: true
    on:
      repo: mole-ids/mole
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^master$|^v[0-9.]+$
  