
language: go
os:
  - linux
  - osx

go:
  - 1.15.x

git:
  depth: false

services:
  - docker

env:
  global:
    - STRUCTOR_VERSION=v1.10.0
    - STRUCTOR_LATEST_TAG=v0.1.2
    - GO111MODULE=on
    - CGO_ENABLED=1

install:
  - >
    if [ x"$TRAVIS_OS_NAME" = x"linux" ]; then
      sudo -E apt-get -yq update;
      sudo -E apt-get -yqq --no-install-suggests --no-install-recommends install \
        build-essential \
        autoconf \
        libtool \
        bison \
        flex \
        make \
        libssl-dev \
        libpcap-dev \
        gcc-multilib \
        g++-multilib \
        && sudo -E ./.travis/pfring-install.sh \
        && sudo -E ./.travis/install-yara.sh
    fi
  - >
    if [ x"$TRAVIS_OS_NAME" = x"osx" ]; then
      if [ -z $TRAVIS_TAG ]; then
        exit 0
      fi
    fi

before_script:
  - >
    if [ x"$TRAVIS_OS_NAME" = x"linux" ]; then
      go mod download
    fi

script:
  - >
    if [ x"$TRAVIS_OS_NAME" = x"linux" ]; then
      make test-race
    fi

before_deploy:
  - ./.travis/before_deploy.sh

deploy:
  - provider: pages
    token: ${GITHUB_TOKEN}
    edge: false
    strategy: git
    local_dir: site
    skip_cleanup: true
    on:
      condition: $TRAVIS_OS_NAME = linux
      repo: mole-ids/mole
      all_branches: true
  
  - provider: releases
    api_key: ${GITHUB_TOKEN}
    file_glob: true
    file: build/mole*
    overwrite: true
    skip_cleanup: true
    draft: false
    on:
      repo: mole-ids/mole
      tags: true
