
language: go
os:
  - linux
  - osx

go:
  - 1.15.x

git:
  depth: false

services:
  - docker

env:
  global:
    - STRUCTOR_VERSION=v1.10.0
    - STRUCTOR_LATEST_TAG=v0.0.0
    - GO111MODULE=on
    - CGO_ENABLED=1

install:
  - >
    if [ $TRAVIS_OS_NAME = linux ]; then
      sudo -E apt-get -yq update;
      sudo -E apt-get -yqq --no-install-suggests --no-install-recommends install \
        build-essential \
        autoconf \
        libtool \
        bison \
        flex \
        make \
        libmagic-dev \
        libssl-dev \
        libpcap-dev \
        gcc-multilib \
        g++-multilib \
        && sudo -E ./travis/travis_pfring.sh
    fi

before_script:
  - go mod download

script:
  - make test-race

before_deploy:
  - ./.travis/before_deploy.sh

deploy:
  - provider: pages
    token: ${GITHUB_TOKEN}
    edge: false
    strategy: git
    local_dir: site
    skip_cleanup: true
    on:
      repo: mole-ids/mole
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^master$|^v[0-9.]+$
  
  - provider: releases
    api_key: ${GITHUB_TOKEN}
    file_glob: true
    file: build/mole*
    overwrite: true
    skip_cleanup: true
    draft: false
    on:
      repo: mole-ids/mole
      all_branches: true
      tags: true
